apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-tp2-deployment
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: k8-tp2
          image: mmumshad/simple-webapp-color
          ports:
            - containerPort: 80
          env:
            - name: color
              value: rouge
