apiVersion: v1
kind: Pod
metadata:
  name: k8s-pod-blue
  namespace: production
  labels:
    app: web
spec:
  containers:
     - name: k8-tp3
       image: mmumshad/simple-webapp-color
       ports:
         - containerPort: 80
       env:
         - name: APP_COLOR
           value: blue
