apiVersion: v1
kind: Pod
metadata:
  name: mysql-volume
  labels:
    app: web
spec:
  containers:
     - name: k8s-mysql
       image: mysql
       volumeMounts:
         - mountPath: /opt
           name: data-volume
       env:
         - name: MYSQL_ROOT_PASSWORD
           value: password
       ports:
        - containerPort: 3306
          name: mysql
  volumes:
         - name: data-volume
           hostPath:
             path: /data-volume
             type: Directory
